<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="admin-PC" failures="1" tests="7" name="Test" time="0.115" errors="0" timestamp="2024-09-25T17:06:13 IST">
  <testcase classname="testNG.NewClass" name="TC_1" time="0.015"/>
  <testcase classname="testNG.NewClass" name="TC_2" time="0.003"/>
  <testcase classname="testNG.NewClass" name="TC_3" time="0.004"/>
  <testcase classname="testNG.NewClass" name="TC_4" time="0.002">
    <skipped/>
  </testcase> <!-- TC_4 -->
  <testcase classname="testNG.NewClass" name="TC_4" time="0.002">
    <skipped/>
  </testcase> <!-- TC_4 -->
  <testcase classname="testNG.NewClass" name="TC_4" time="0.002">
    <skipped/>
  </testcase> <!-- TC_4 -->
  <testcase classname="testNG.NewClass" name="TC_4" time="0.003">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [16] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [16] but found [10]
at testNG.NewClass.TC_4(NewClass.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC_4 -->
</testsuite> <!-- Test -->
